name: oc

on:
  pull_request:
    branches: [ main ]

jobs:
  oc-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.3
        with:
          dns ip: 8.8.8.8
          oc version: 'v3.11.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: npm i
      - name: Deploy
        run: npm run openshift
